"""Worker-facing consultation & analysis strings (excludes municipality/company coordination)."""


def register_strings(s) -> None:
    # --- index.support (worker consultation) ---
    s("index.support.copy",
      "해외 근로자의 고충을 단순 이탈 위험으로 분류하지 않고, 근무·안전·생활·소통의 원인을 확인해 지원 가능한 경로로 연결합니다.",
      "විදේශීය සේවකයින්ගේ ගැටළු නිකම්ම ඉවත්වීමේ අවදානමක් ලෙස නොව, වැඩ·ආරක්ෂාව·ජීවිතය·සන්නිවේදනයේ හේතු හඳුනා සහාය මාර්ගයට සම්බන්ධ කරයි.",
      "We do not treat workers' difficulties as simple attrition risk—we identify causes in work, safety, living, and communication and connect to support paths.",
      "不把海外劳动者的困难简单归类为流失风险，而是确认工作、安全、生活与沟通方面的原因并连接到可支持的路径。",
      "Hindi simpleng attrition risk ang mga hirap ng manggagawa—tukuyin ang sanhi sa trabaho, kaligtasan, pamumuhay, at komunikasyon at ikonekta sa suporta.",
      "ไม่จัดประเภทความลำบากของแรงงานเป็นแค่ความเสี่ยงลาออก แต่ตรวจสาเหตุด้านงาน ความปลอดภัย ชีวิต และการสื่อสาร แล้วเชื่อมสู่เส้นทางช่วยเหลือ",
      "غیر ملکی کارکنوں کی مشکلات کو صرف اخراج کے خطرے میں نہیں رکھتے—کام، حفاظت، زندگی اور بات چیت کی وجوہات جانچ کر مدد کے راستے سے جوڑتے ہیں۔",
      "Xorijiy ishchilarning qiyinchiliklarini oddiy ketish xavfi deb emas, ish, xavfsizlik, turmush va muloqot sabablarini aniqlab yordam yo'llariga bog'laymiz.",
      "Чет элдик эмгекчилердин кыйынчылыктарын жөн гана кетүү тобокелдиги деп эмес, иш, коопсуздук, жашоо жана баарлашуу себептерин аныктап колдоо жолдоруна туташтырабыз.")

    s("index.worker.card.title", "근로자 통합 관리 카드", "සේවක ඒකාබද්ධ කළමනාකරණ කාඩ්පත", "Worker integrated management card", "劳动者综合管理卡", "Integrated na card ng manggagawa", "บัตรจัดการแรงงานแบบบูรณาการ", "کارکن کا مربوط انتظامی کارڈ", "Ishchi integratsiyalangan boshqaruv kartasi", "Эмгекчи интеграцияланган башкаруу картасы")
    s("index.worker.card.subtitle", "개인별 교육 · 상담 · 점검 · 변화 이력", "පුද්ගලික අධ්‍යාපනය · සාකච්ඡා · පරීක්ෂාව · වෙනස්වීම් ඉතිහාසය", "Individual education · consultation · checks · change history", "个人教育·咨询·检查·变更记录", "Indibidwal na edukasyon · konsultasyon · pagsusuri · kasaysayan ng pagbabago", "การศึกษา·ปรึกษา·ตรวจสอบ·ประวัติการเปลี่ยนแปลงรายบุคคล", "انفرادی تعلیم · مشاورت · جانچ · تبدیلی کی تاریخ", "Shaxsiy ta'lim · maslahat · tekshiruv · o'zgarish tarixi", "Жеке окутуу · кеңеш · текшерүү · өзгөрүү тарыхы")
    s("index.worker.card.status", "적응 확인 중", "අනුවර්තනය පරීක්ෂා කරමින්", "Adaptation check in progress", "适应确认中", "Sinusuri ang pag-aangkop", "กำลังตรวจสอบการปรับตัว", "موافقت کی جانچ جاری", "Moslashuv tekshirilmoqda", "Бейиш текшерилүүдө")

    s("index.worker.timeline1.title", "입국 후 동반교육 완료", "ආගමනයෙන් පසු එක්ව අධ්‍යාපනය සම්පූර්ණ", "Post-arrival co-education completed", "入境后协同教育完成", "Tapos na ang ko-edukasyon pagkatapos ng pagdating", "เสร็จสิ้นการศึกษาร่วมหลังเข้าประเทศ", "آمد کے بعد مشترکہ تعلیم مکمل", "Kelgandan keyin hamkor ta'lim yakunlandi", "Келгенден кийин кошумча окутуу аяктады")
    s("index.worker.timeline1.desc", "근로자 교육 이수 확인", "සේවක අධ්‍යාපන සම්පූර්ණතාව තහවුරු", "Worker training completion confirmed", "劳动者教育完成确认", "Nakumpirma ang pagtatapos ng training ng manggagawa", "ยืนยันการเรียนจบของแรงงาน", "کارکن کی تعلیم کی تکمیل کی تصدیق", "Ishchi ta'limini tugatgani tasdiqlandi", "Эмгекчинин окутуусу аяктаганы ырасталды")
    s("index.worker.timeline2.title", "생활·근무 적응 점검", "ජීවිතය·වැඩ අනුවර්තන පරීක්ෂාව", "Living & work adaptation check", "生活·工作适应检查", "Pagsusuri sa pag-aangkop sa buhay at trabaho", "ตรวจสอบการปรับตัวด้านชีวิตและงาน", "زندگی اور کام کی موافقت کی جانچ", "Turmush va ish moslashuvi tekshiruvi", "Жашоо·иш бейиш текшерүүсү")
    s("index.worker.timeline2.desc", "주거·교통·현장 소통 상태 확인", "නිවාස·ප්‍රවාහන·ක්ෂේත්‍ර සන්නිවේදන තත්ත්වය පරීක්ෂා", "Housing, transport, on-site communication status check", "确认居住·交通·现场沟通状态", "Suriin ang tirahan, transportasyon, komunikasyon sa site", "ตรวจสถานะที่พัก การเดินทาง การสื่อสารในหน้างาน", "رہائش، نقل و حمل، سائٹ پر بات چیت کی حالت", "Turar joy, transport, maydonda muloqot holati", "Турак жай, унаа, аянттагы баарлашуу абалы")
    s("index.worker.timeline3.title", "상담 요청 후 후속 확인", "සාකච්ඡා ඉල්ලීමෙන් පසු පසු විමර්ශනය", "Follow-up after consultation request", "咨询请求后后续确认", "Follow-up pagkatapos ng kahilingan sa konsultasyon", "ติดตามหลังคำขอปรึกษา", "مشاورت کی درخواست کے بعد فالو اپ", "Maslahat so'rovidan keyin kuzatuv", "Кеңеш суроосунан кийин кийинки текшерүү")
    s("index.worker.timeline3.desc", "지원 연계·다음 점검일 기록", "සහාය සම්බන්ධතාව·ඊළඟ පරීක්ෂා දිනය සටහන්", "Support linkage and next check date recorded", "记录支持衔接与下次检查日", "Naitala ang suporta at susunod na petsa ng pagsusuri", "บันทึกการเชื่อมต่อการช่วยเหลือและวันตรวจครั้งถัดไป", "مدد کا تعلق اور اگلی جانچ کی تاریخ درج", "Yordam bog'lanishi va keyingi tekshiruv sanasi yozildi", "Колдоо байланышы жана кийинки текшерүү күнү жазылды")

    s("index.worker.legal.kicker", "AI법친 연계 모듈", "AI නීති මිතුර සම්බන්ධතා මොඩියුලය", "AI Legal Buddy link module", "AI法亲联动模块", "AI Legal Buddy link module", "โมดูลเชื่อม AI Legal Buddy", "AI قانونی ساتھی لنک ماڈیول", "AI huquqiy yordamchi bog'lanish moduli", "AI укук жардамчысы байланыш модулу")
    s("index.worker.legal.title", "문제가 생겼을 때,<br>모국어로 먼저 정리합니다.", "ගැටළුවක් ඇති වූ විට,<br>මව් භාෂාවෙන් පළමුව සංවිධානය කරමු.", "When a problem arises,<br>we organize it first in your language.", "出现问题时，<br>先用母语整理。", "Kapag may problema,<br>una itong aayusin sa iyong wika.", "เมื่อเกิดปัญหา<br>จัดระเบียบด้วยภาษาแม่ก่อน", "جب مسئلہ ہو<br>پہلے مادری زبان میں ترتیب دیں۔", "Muammo paydo bo'lganda,<br>avval ona tilingizda tartibga solamiz.", "Кыйынчылык чыкса,<br>алгач эне тилиңизде түзөбүз.")
    s("index.worker.legal.copy", "AI법친은 법률 결과를 단정하지 않습니다. 사용자의 상황을 정리하고 필요한 자료·절차를 안내한 뒤 운영센터와 전문가 지원 경로로 연결합니다.", "AI නීති මිතුර නීතිමය ප්‍රතිඵල නිශ්චිතව නොකියයි. ඔබේ තත්ත්වය සංවිධානය කර අවශ්‍ය දත්ත·පියවර පෙන්වා මෙහෙයුම් මධ්‍යස්ථානයට සම්බන්ධ කරයි.", "AI Legal Buddy does not determine legal outcomes. It organizes your situation, guides required documents and steps, then connects to the operations center and expert support.", "AI法亲不判定法律结果，先整理您的情况、指引所需资料与程序，再连接运营中心与专家支持。", "Hindi tumutukoy ang AI Legal Buddy ng legal na resulta—aayusin ang sitwasyon, gabayan ang mga dokumento at hakbang, at ikonekta sa operations center.", "AI Legal Buddy ไม่ตัดสินผลทางกฎหมาย จัดระเบียบสถานการณ์ แนะนำเอกสารและขั้นตอน แล้วเชื่อมศูนย์ปฏิบัติการ", "AI قانونی ساتھی قانونی نتیجہ نہیں بتاتا—صورت حال ترتیب دے، دستاویزات و طریقہ بتائے، پھر آپریشنز سینٹر سے جوڑے۔", "AI huquqiy yordamchi huquqiy natija bermaydi—holatni tartibga soladi, hujjat va tartibni ko'rsatadi, operatsiya markaziga bog'laydi.", "AI укук жардамчысы укуктук натыйжаны аныктабайт—абалды түзөт, документтерди жана кадамдарды көрсөтөт, операциялык борборго туташтырат.")
    s("index.worker.legal.item1", "급여·근로계약 관련 어려움", "වැටුප්·සේවා ගිවිසුම් ගැටළු", "Wage & employment contract difficulties", "工资·劳动合同相关困难", "Problema sa sahod at kontrata", "ปัญหาเกี่ยวกับค่าจ้างและสัญญาจ้าง", "تنخواہ اور معاہدے کے مسائل", "Ish haqi va mehnat shartnomasi qiyinchiliklari", "Эмгек акы жана келишим кыйынчылыктары")
    s("index.worker.legal.item2", "산업안전·사고·근무 환경 우려", "කර්මාන්ත ආරක්ෂාව·අනතුර·වැඩ පරිසර ගැටළු", "Industrial safety, accidents, work environment concerns", "工业安全·事故·工作环境担忧", "Kaligtasan, aksidente, kapaligiran sa trabaho", "ความกังวลด้านความปลอดภัย อุบัติเหตุ สภาพแวดล้อม", "صنعتی حفاظت، حادثات، کام کے ماحول کی فکر", "Sanoat xavfsizligi, baxtsiz hodisa, ish muhiti", "Өнөр жай коопсуздугу, кырсык, иш чөйрөсү")
    s("index.worker.legal.item3", "체류·변경 절차와 필요한 서류", "නැවතීම·වෙනස් කිරීමේ පියවර සහ ලේඛන", "Stay & change procedures and required documents", "居留·变更程序与所需文件", "Pamamalagi at pagbabago ng dokumento", "ขั้นตอนการพำนัก·เปลี่ยนแปลงและเอกสาร", "قیام اور تبدیلی کے طریقے و دستاویزات", "Yashash va o'zgarish tartibi hamda hujjatlar", "Жашоо·өзгөрүү тартиби жана документтер")
    s("index.worker.legal.btn", "AI법친 연계 흐름 보기", "AI නීති මිතුර ප්‍රවාහය බලන්න", "View AI Legal Buddy flow", "查看AI法亲联动流程", "Tingnan ang daloy ng AI Legal Buddy", "ดูขั้นตอน AI Legal Buddy", "AI قانونی ساتھی کا عمل دیکھیں", "AI yordamchi oqimini ko'rish", "AI жардамчысынын агымын көрүү")

    # --- analysis instructions ---
    s("index.worker.analysis.title", "개별 상담·분석 지시", "පුද්ගලික සාකච්ඡා·විශ්ලේෂණ උපදෙස්", "Individual consultation & analysis guidance", "个别咨询·分析指示", "Gabay sa indibidwal na konsultasyon at pagsusuri", "คำแนะนำการปรึกษาและวิเคราะห์รายบุคคล", "انفرادی مشاورت و تجزیہ کی ہدایات", "Shaxsiy maslahat va tahlil ko'rsatmalari", "Жеке кеңеш жана талдоо көрсөтмөлөрү")
    s("index.worker.analysis.step1", "① 모국어로 상황·증상·요청 내용을 기록합니다.", "① මව් භාෂාවෙන් තත්ත්වය·ලක්ෂණ·ඉල්ලීම් සටහන් කරන්න.", "① Record situation, symptoms, and requests in your language.", "① 用母语记录情况、症状与请求内容。", "① Itala ang sitwasyon, sintomas, at kahilingan sa iyong wika.", "① บันทึกสถานการณ์ อาการ และคำขอด้วยภาษาแม่", "① صورت حال، علامات اور درخواست مادری زبان میں درج کریں۔", "① Holat, belgilar va so'rovlarni ona tilingizda yozing.", "① Абал, белгилер жана суроолорду эне тилиңизде жазыңыз.")
    s("index.worker.analysis.step2", "② 위험 신호(안전·생활·소통)를 분류하고 우선순위를 정합니다.", "② අවදානම් සංඥා (ආරක්ෂාව·ජීවිතය·සන්නිවේදනය) වර්ගීකරණය කර ප්‍රමුඛතාව දෙන්න.", "② Classify risk signals (safety, living, communication) and set priority.", "② 分类风险信号（安全·生活·沟通）并确定优先级。", "② Uriin ang risk signals (kaligtasan, pamumuhay, komunikasyon) at unahin.", "② จัดประเภทสัญญาณเสี่ยง (ความปลอดภัย ชีวิต การสื่อสาร) และกำหนดลำดับ", "② خطرے کی نشانیاں (حفاظت، زندگی، بات چیت) درجہ بندی کریں۔", "② Xavf signallarini (xavfsizlik, turmush, muloqot) ajrating va ustuvorlik bering.", "② Коопсуздук·жашоо·баарлашуу тобокелдик белгилерин классификациялаңыз.")
    s("index.worker.analysis.step3", "③ 필요한 지원·상담·후속 점검 경로를 안내하고 다음 일정을 알립니다.", "③ අවශ්‍ය සහාය·සාකච්ඡා·පසු විමර්ශන මාර්ගය පෙන්වා ඊළඟ දිනය දන්වන්න.", "③ Guide support, consultation, and follow-up paths and notify the next schedule.", "③ 指引所需支持·咨询·后续检查路径并告知下次日程。", "③ Gabayan ang suporta, konsultasyon, follow-up at ipaalam ang susunod na iskedyul.", "③ แนะนำเส้นทางช่วยเหลือ ปรึกษา ติดตาม และแจ้งกำหนดถัดไป", "③ مدد، مشاورت، فالو اپ کے راستے بتائیں اور اگلی تاریخ دیں۔", "③ Yordam, maslahat, kuzatuv yo'llarini ko'rsating va keyingi sanani ayting.", "③ Колдоо, кеңеш, кийинки текшерүү жолдорун көрсөтүңүз.")

    # --- phone mockup ---
    s("index.worker.phone.title", "오늘 필요한<br>현장 안내를 확인하세요", "අද අවශ්‍ය<br>ක්ෂේත්‍ර මාර්ගෝපදේශනය බලන්න", "Check today's<br>on-site guidance", "请确认今天所需的<br>现场指引", "Tingnan ang gabay sa site<br>para ngayon", "ตรวจสอบคำแนะนำ<br>หน้างานวันนี้", "آج کی سائٹ<br>ہدایات دیکھیں", "Bugungi maydon<br>ko'rsatmalarini ko'ring", "Бүгүнкү аянт<br>жетекчилигин караңыз")
    s("index.worker.phone.job", "제조업 · 입국 28일차", "නිෂ්පාදන · ආගමනය 28 වන දින", "Manufacturing · Day 28", "制造业 · 入境第28天", "Manufacturing · Araw 28", "การผลิต · วันที่ 28", "مینوفیکچرنگ · 28واں دن", "Ishlab chiqarish · 28-kun", "Өндүрүү · 28-күн")
    s("index.worker.phone.status", "정상", "සාමාන්‍ය", "Normal", "正常", "Normal", "ปกติ", "معمول", "Oddiy", "Кадимки")
    s("index.worker.phone.row1", "작업 전 안전 매뉴얼", "වැඩ පටන් ගැනීමට පෙර ආරක්ෂක මාර්ගෝපදේශ", "Pre-work safety manual", "作业前安全手册", "Manual ng kaligtasan bago magtrabaho", "คู่มือความปลอดภัยก่อนทำงาน", "کام سے پہلے حفاظتی دستی کتاب", "Ishdan oldin xavfsizlik qo'llanmasi", "Иш башталганча коопсуздук колдонмосу")
    s("index.worker.phone.row2", "동반교육 이수", "එක්ව අධ්‍යාපනය සම්පූර්ණ", "Co-education completed", "协同教育完成", "Tapos na ang ko-edukasyon", "เรียนจบการศึกษาร่วม", "مشترکہ تعلیم مکمل", "Hamkor ta'lim tugallandi", "Кошумча окутуу аяктады")
    s("index.worker.phone.row3", "도움 요청 / AI법친", "උදව් ඉල්ලීම / AI නීති මිතුර", "Help request / AI Legal Buddy", "求助 / AI法亲", "Hiling ng tulong / AI Legal Buddy", "ขอความช่วยเหลือ / AI Legal Buddy", "مدد / AI قانونی ساتھی", "Yordam so'rovi / AI yordamchi", "Жардам / AI жардамчы")
    s("index.worker.phone.badge1", "확인", "තහවුරු", "View", "确认", "Tingnan", "ดู", "دیکھیں", "Ko'rish", "Көрүү")
    s("index.worker.phone.badge2", "완료", "සම්පූර්ණ", "Done", "完成", "Tapos", "เสร็จ", "مکمل", "Tugallandi", "Аяктады")
    s("index.worker.phone.badge3", "열기", "විවෘත", "Open", "打开", "Buksan", "เปิด", "کھولیں", "Ochish", "Ачуу")

    # --- app mockup ---
    s("index.worker.app.title", "제조업 · 프레스 작업<br>오늘의 안전 안내", "නිෂ්පාදන · ප්‍රෙස් වැඩ<br>අද ආරක්ෂක මාර්ගෝපදේශ", "Manufacturing · Press work<br>Today's safety guide", "制造业·冲压作业<br>今日安全指引", "Manufacturing · Press<br>Gabay sa kaligtasan ngayon", "การผลิต · งานปั๊ม<br>คำแนะนำความปลอดภัยวันนี้", "مینوفیکچرنگ · پریس کام<br>آج کی حفاظتی ہدایت", "Ishlab chiqarish · Press ishi<br>Bugungi xavfsizlik", "Өндүрүү · пресс иши<br>Бүгүнкү коопсуздук")
    s("index.worker.app.taskTitle", "작업 시작 전 확인", "වැඩ ආරම්භ කිරීමට පෙර පරීක්ෂාව", "Pre-work checklist", "作业开始前确认", "Checklist bago magsimula", "ตรวจสอบก่อนเริ่มงาน", "کام شروع سے پہلے چیک", "Ish boshlashdan oldin tekshiruv", "Иш баштоодон мурун текшерүү")
    s("index.worker.app.taskDesc", "보호장비를 먼저 착용하고, 기계 주변의 위험요소를 확인하세요.", "පළමුව ආරක්ෂක ඇඳුම් ඇඳ, යන්ත්‍ර අවට අවදානම් පරීක්ෂා කරන්න.", "Wear protective gear first and check hazards around the machine.", "请先穿戴防护装备，并确认机器周围危险因素。", "Magsuot muna ng protective gear at suriin ang panganib sa makina.", "สวมอุปกรณ์ป้องกันก่อน แล้วตรวจอันตรายรอบเครื่องจักร", "پہلے حفاظتی سامان پہنیں اور مشین کے ارد گرد خطرات دیکھیں۔", "Avval himoya vositalarini kiying va mashina atrofidagi xavflarni tekshiring.", "Алгач коргоо кийимин кийип, машина айланасындагы тобокелдерди текшериңиз.")
    s("index.worker.app.check1", "보호장비 착용 방법 보기", "ආරක්ෂක ඇඳුම් ඇඳීමේ ක්‍රමය බලන්න", "How to wear protective gear", "查看防护装备穿戴方法", "Paano magsuot ng protective gear", "ดูวิธีสวมอุปกรณ์ป้องกัน", "حفاظتی سامان پہننے کا طریقہ", "Himoya vositalarini kiyish usuli", "Коргоо кийимин кийүү ыкмасы")
    s("index.worker.app.check2", "위험 행동 확인하기", "අවදානම් හැසිරීම් පරීක්ෂා කරන්න", "Check risky behaviors", "确认危险行为", "Suriin ang mapanganib na kilos", "ตรวจพฤติกรรมเสี่ยง", "خطرناک رویے چیک کریں", "Xavfli xatti-harakatlarni tekshiring", "Коопсузсуз аракеттерди текшерүү")
    s("index.worker.app.check3", "사고 시 관리자 호출 방법", "අනතුරකදී කළමනාකරුට දැනුම් දීම", "How to call a supervisor in an accident", "事故时呼叫管理员的方法", "Paano tawagan ang supervisor kapag may aksidente", "วิธีเรียกหัวหน้าเมื่อเกิดอุบัติเหตุ", "حادثے میں سپروائزر کو بلانے کا طریقہ", "Baxtsiz hodisada menejerni chaqirish", "Кырсыкта жетекчини чакыруу")
    s("index.worker.app.cta", "이해 확인하고 이수 저장하기", "තේරුම් පරීක්ෂා කර සම්පූර්ණතාව සුරකින්න", "Confirm understanding and save completion", "确认理解并保存完成记录", "Kumpirmahin ang pag-unawa at i-save", "ยืนยันความเข้าใจและบันทึกการเรียนจบ", "سمجھ کی تصدیق کریں اور محفوظ کریں", "Tushunishni tasdiqlang va saqlang", "Түшүнүктү ырастаңыз жана сактаңыз")

    # --- operations dashboard (individual consultation) ---
    s("index.worker.ops.metric1.label", "신규 상담 접수", "නව සාකච්ඡා ලැබීම්", "New consultation intake", "新咨询受理", "Bagong konsultasyon", "รับคำปรึกษาใหม่", "نئی مشاورت", "Yangi maslahat qabuli", "Жаңы кеңеш кабыл алуу")
    s("index.worker.ops.metric1.em", "담당 배정 필요", "භාරකරු පවරා ගැනීම අවශ්‍ය", "Assignment needed", "需分配负责人", "Kailangan ng assignment", "ต้องมอบหมายผู้รับผิดชอบ", "تفویض ضروری", "Mas'ul biriktirish kerak", "Жооптуу дайындоо керек")
    s("index.worker.ops.metric2.label", "후속 점검 예정", "පසු විමර්ශන නියමිත", "Follow-up checks scheduled", "后续检查预定", "Naka-iskedyul na follow-up", "ตรวจติดตามที่กำหนด", "فالو اپ طے", "Kuzatuv tekshiruvi rejalashtirilgan", "Кийинки текшерүү пландаштырылган")
    s("index.worker.ops.metric2.em", "7·30·90일 기준", "7·30·90 දින මාර්ගෝපදේශ", "7·30·90 day basis", "7·30·90天标准", "Batay sa 7·30·90 araw", "ตามเกณฑ์ 7·30·90 วัน", "7·30·90 دن کا معیار", "7·30·90 kun asosida", "7·30·90 күн негизинде")
    s("index.worker.ops.metric3.label", "전문가 연계 진행", "විශේෂඥ සම්බන්ධතා ප්‍රගතිය", "Expert referral in progress", "专家转介进行中", "Expert referral ongoing", "กำลังเชื่อมผู้เชี่ยวชาญ", "ماہر رجوع جاری", "Mutaxassis bog'lanishi", "Адис байланышы")
    s("index.worker.ops.metric3.em", "운영자 확인 중", "මෙහෙයුම්කරු පරීක්ෂා කරමින්", "Operator reviewing", "运营人员确认中", "Sinusuri ng operator", "เจ้าหน้าที่กำลังตรวจ", "آپریٹر جائزہ لے رہا ہے", "Operator tekshirmoqda", "Оператор текшерүүдө")
    s("index.worker.ops.metric4.label", "분석·지시 대기", "විශ්ලේෂණ·උපදෙස් බලාපොරොත්තු", "Analysis & guidance pending", "分析·指示待处理", "Naghihintay ng pagsusuri", "รอการวิเคราะห์·คำแนะนำ", "تجزیہ·ہدایت زیر التوا", "Tahlil va ko'rsatma kutilmoqda", "Талдоо·көрсөтмө күтүлүүдө")
    s("index.worker.ops.metric4.em", "개별 상담 건", "පුද්ගලික සාකච්ඡා කේස", "Individual consultation cases", "个别咨询件", "Indibidwal na konsultasyon", "เคสปรึกษารายบุคคล", "انفرادی مشاورت", "Shaxsiy maslahatlar", "Жеке кеңештер")
    s("index.worker.ops.flowTitle", "개별 상담 처리 흐름", "පුද්ගලික සාකච්ඡා සැකසුම් ප්‍රවාහය", "Individual consultation workflow", "个别咨询处理流程", "Daloy ng indibidwal na konsultasyon", "ขั้นตอนการปรึกษารายบุคคล", "انفرادی مشاورت کا عمل", "Shaxsiy maslahat jarayoni", "Жеке кеңеш процесси")
    s("index.worker.ops.flow1", "접수·모국어 기록", "ලැබීම·මව් භාෂා සටහන", "Intake · native-language record", "受理·母语记录", "Intake · rekord sa sariling wika", "รับเรื่อง·บันทึกภาษาแม่", "قبول·مادری زبان میں ریکارڈ", "Qabul · ona tili yozuvi", "Кабыл алуу·эне тили жазуусу")
    s("index.worker.ops.flow2", "상황 분석·위험 신호 분류", "තත්ත්ව විශ්ලේෂණ·අවදානම් වර්ගීකරණය", "Situation analysis · risk classification", "情况分析·风险信号分类", "Pagsusuri · pag-uuri ng risk", "วิเคราะห์สถานการณ์·จัดประเภทความเสี่ยง", "تجزیہ·خطرے کی درجہ بندی", "Tahlil · xavf tasnifi", "Талдоо·тобокелдик классификациясы")
    s("index.worker.ops.flow3", "지원·후속 점검 지시", "සහාය·පසු විමර්ශන උපදෙස්", "Support · follow-up check directive", "支持·后续检查指示", "Suporta · direktiba sa follow-up", "ช่วยเหลือ·สั่งติดตาม", "مدد·فالو اپ ہدایت", "Yordam · kuzatuv ko'rsatmasi", "Колдоо·кийинки текшерүү көрсөтмөсү")
    s("index.worker.ops.priorityTitle", "오늘의 개별 상담 우선 처리", "අද පුද්ගලික සාකච්ඡා ප්‍රමුඛතාව", "Today's priority individual consultations", "今日个别咨询优先处理", "Prayoridad na konsultasyon ngayon", "ปรึกษารายบุคคลที่ต้องทำวันนี้", "آج کی ترجیحی مشاورتیں", "Bugungi ustuvor shaxsiy maslahatlar", "Бүгүнкү приоритеттүү жеке кеңештер")
    s("index.worker.ops.priority1", "긴급 안전 확인 상담", "හදිසි ආරක්ෂක සාකච්ඡා", "Urgent safety consultation", "紧急安全确认咨询", "Urgenteng konsultasyon sa kaligtasan", "ปรึกษาความปลอดภัยฉุกเฉิน", "فوری حفاظتی مشاورت", "Shoshilinch xavfsizlik maslahati", "Шашылыш коопсуздук кеңеши")
    s("index.worker.ops.priority2", "생활·소통 어려움 분석", "ජීවිතය·සන්නිවේදන ගැටළු විශ්ලේෂණය", "Living & communication difficulty analysis", "生活·沟通困难分析", "Pagsusuri sa hirap sa buhay at komunikasyon", "วิเคราะห์ปัญหาชีวิต·การสื่อสาร", "زندگی·بات چیت کی مشکل کا تجزیہ", "Turmush va muloqot qiyinchilik tahlili", "Жашоо·баарлашуу кыйынчылыгын талдоо")
    s("index.worker.ops.priority3", "체류·변경 절차 안내 상담", "නැවතීම·වෙනස් කිරීමේ පියවර සාකච්ඡා", "Stay & change procedure consultation", "居留·变更程序咨询", "Konsultasyon sa pamamalagi at pagbabago", "ปรึกษาขั้นตอนพำนัก·เปลี่ยนแปลง", "قیام·تبدیلی کے طریقے کی مشاورت", "Yashash va o'zgarish tartibi maslahati", "Жашоо·өзгөрүү тартиби боюнча кеңеш")

    s("common.nav.supportWorker", "상담·지원", "සාකච්ඡා·සහාය", "Consultation & support", "咨询·支持", "Konsultasyon at suporta", "ปรึกษา·สนับสนุน", "مشاورت·مدد", "Maslahat va yordam", "Кеңеш·колдоо")
    s("common.nav.educationWorker", "다국어 교육", "බහුභාෂා අධ්‍යාපනය", "Multilingual training", "多语言教育", "Multilingual na training", "การศึกษาหลายภาษา", "کثیر لسانی تعلیم", "Ko'p tilli ta'lim", "Көп тилдүү окутуу")
